FIX: feat/staff
arayhan/aflowz-dc-web pull request #6
Opened 2022-12-01 14:08 UTC by thareqkemaal

2022-12-01 14:18 UTC, arayhan requested changes
Tabelnya coba dibikin komponen terpisah req, kaya komponen tabel yang lain. kalau tabelnya ga sekompleks ada pagination, etc. bisa taro di folder molecules/TableDetail

2022-12-01 14:18 UTC, arayhan commented on src/pages/Staff/StaffDetail.jsx
> +	const columns2 = useMemo(
Ini tabel 1 dan tabel 2-nya better dipisah jadi satu komponen aja req, biar ga kepanjangan plus kalo ada komponen lain yang butuh tinggal panggil. prevent duplicate code juga.

2022-12-01 14:29 UTC, thareqkemaal commented on src/pages/Staff/StaffDetail.jsx
> +	const columns2 = useMemo(
oke siap bang

2022-12-02 17:38 UTC, thareqkemaal commented
sudah di push lagi dengan request terbaru, nanti akan di cek/refactor lagi setelah success merge.

2022-12-02 17:52 UTC, arayhan commented on src/store/city.store.js
> +import { get } from 'react-hook-form';
get yg ini ga dipake kan ya mas? boleh minta tolong remove dulu ndak mas'e?

2022-12-02 17:54 UTC, arayhan commented on src/services/province.service.js
> +		const queryParams = objectToQueryString(reqQuery); // Indonesia
ini mungkin bisa disimplify jadi kaya gini mas :
`objectToQueryString({ country_id: 100, ...params })`

2022-12-03 09:57 UTC, merged